[features]
seeds = false
skip-lint = false

[programs.localnet]
goty_voting = "Bb4F9xrbrxHrDbHuosgGSsmJFF7iyNs1BCwYf4R54w6K"

[programs.devnet]
goty_voting = "Bb4F9xrbrxHrDbHuosgGSsmJFF7iyNs1BCwYf4R54w6K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"
